trigger:
- main

pool:
  name: Azure Pipelines

variables:
  BuildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'COMP367Quiz4/COM367Quiz4/COM367Quiz4.sln'
    arguments: '--configuration $(BuildConfiguration)'
  displayName: 'Build ASP.NET project'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
    arguments: '--configuration $(BuildConfiguration)'
  displayName: 'Run unit tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'run'
    workingDirectory: 'COMP367Quiz4/COM367Quiz4/COM367Quiz4'
  displayName: 'Run ASP.NET project'

agent:
  vmImage: 'ubuntu-latest'
  agent: 'Hosted Agent'
  version: '3.218.0'
